set -g mouse on
setw -g mode-keys vi
set -g status-position top

set -g allow-rename off
set -g automatic-rename off
set -g extended-keys on

# Handle the Colorscheme
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Screensaver
set -g lock-after-time 120 # 2 * 60 -> 2 mins
set -g lock-command 'cmatrix -ab -u 2'

# Reload the Tmux config
unbind r
bind r source-file ~/.tmux.conf

# Vim Style splits
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# -------------------
# ----- Plugins -----
# -------------------

## catppuccin/tmux
set -g @catppuccin_flavor 'mocha'
# set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "default"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"


## tmux-plugins/tmux-cpu
run '~/.config/tmux/plugins/tmux-cpu/cpu.tmux'


## tmux-plugins/tmux-battery
run '~/.config/tmux/plugins/tmux-battery/battery.tmux'
